### ISSUE TITLE
请问能把demo的源码分享一下吗

### ISSUE THREAD

**Issue by Jony1943** [jiaming743/DataV#1]
我想学一下demo里面的一些效果，谢谢

**Comment by jiaming743** [comment]
2.x组件库的[demo](https://github.com/jiaming743/datav.jiaminghi.com/tree/master/demo)已经上传，1.x组件库已经不提供支持，它们的demo在近期会使用2.x重写。

**Comment by Jony1943** [comment]
就是官网右上角的的demo，一个页面有很多组件，我想学一下那个圆角柱状图和环形图内的动画（文字翻转等等）

**Comment by jiaming743** [comment]
那个demo是使用1.x版本的组件库写的，圆角柱状图和那个环形图的内部动画 都是1.x组件库提供的组件和效果，你可以安装1.x版本的组件库去查看源码

# 步骤

```powershell
mkdir dataview

cd dataview

npm init

// 按回车直到初始化完毕

npm install @jiaminghi/data-view@1
```

安装结束后你可以在**node_modules**文件夹内查看1.x组件库的源码

**圆角柱状图**
`dataview\node_modules\@jiaminghi\data-view\components\capsuleChart`
