### ISSUE TITLE
边框变大之后 ，效果异常

### ISSUE THREAD

**Issue by qiuweikangdev** [jiaming743/DataV#11]
<template>
  <div class="dv-res">
        <el-row>
            <el-col :xs='16' :sm='5' :md='8' :lg='10' :xl='10'> 
                <dv-border-box-1 class="demo-dv1">
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                </dv-border-box-1>
            </el-col>
        </el-row>
  </div>
</template>

<style scoped>
.dv-res >>> .demo-dv1 .border{
    width: 100%;
    height: 100%
}
.dv-res >>> .border-box-content{
     width: 100%;
     height: 100%;

}
.dv-res p{
    color:yellow;
    text-align: center;
}
</style>

1、边框正常显示
![Image 2](https://user-images.githubusercontent.com/44153172/64139984-700d0200-ce35-11e9-91b2-ca52cadc9cc9.png)

2、边框变大之后效果异常  
![Image 1](https://user-images.githubusercontent.com/44153172/64139990-74391f80-ce35-11e9-90be-b9ff38c1c3e5.png)

**Comment by jiaming743** [comment]
变大是什么意思？ @qiuweikangdev

**Comment by qiuweikangdev** [comment]
就是在大屏幕显示的时候，边框就自适应变大，效果就异常了



------------------ 原始邮件 ------------------
发件人: "JM"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 上午10:43
收件人: "jiaming743/DataV"<DataV@noreply.github.com>; 
抄送: "xin "<642827353@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jiaming743/DataV] 边框变大之后 ，效果异常 (#11)




变大是什么意思？ @qiuweikangdev

**Comment by jiaming743** [comment]
是否方便提供一下Vue文件

**Comment by qiuweikangdev** [comment]
<template>
  <div class="dv-res">
        <el-row>
            <el-col :xs='16' :sm='5' :md='8' :lg='10' :xl='5'> 
                <dv-border-box-1 class="demo-dv1">
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                    <p>啊啊啊啊啊啊啊啊</p>
                </dv-border-box-1>
            </el-col>
        </el-row>
  </div>
</template>




<style scoped>
.dv-res >>> .demo-dv1 .border{
    position: absolute;
    display:block;
    width: 100%;
    height: 100%
}
.dv-res >>> .border-box-content{
     width: 100%;
     height: 100%;
     display:block;


}
.dv-res p{
    color:yellow;
    text-align: center;
    font-size: 50px;
}
</style>





------------------ 原始邮件 ------------------
发件人: "JM"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 上午10:46
收件人: "jiaming743/DataV"<DataV@noreply.github.com>; 
抄送: "xin "<642827353@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jiaming743/DataV] 边框变大之后 ，效果异常 (#11)




是否方便提供一下Vue文件

**Comment by qiuweikangdev** [comment]
就是在xl大屏幕的时候，边框就没有那么亮了



------------------ 原始邮件 ------------------
发件人: "JM"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 上午10:46
收件人: "jiaming743/DataV"<DataV@noreply.github.com>; 
抄送: "xin "<642827353@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jiaming743/DataV] 边框变大之后 ，效果异常 (#11)




是否方便提供一下Vue文件

**Comment by jiaming743** [comment]
@qiuweikangdev 我这里好像没有什么问题，可以添加我的QQ:`743192023` 详细描述异常情况

**Comment by jiaming743** [comment]
边框变小系外部容器缩放导致，实际尺寸及效果并无异常
