### ISSUE TITLE
柱形图等新增

### ISSUE THREAD

**Issue by cangyu1993** [jiaming743/DataV#13]
#### 新组件的类型？

* [ ] 边框
* [ ] 装饰
* [ ] 图表
* [x] 其他

#### 这个组件的功能描述 (边框及装饰类，请提供样图)？
看demo网站柱形图没有x轴排列的，后期是否有可能新增这些？图表没有hover效果，像echers那样鼠标方式显示信息是否会增加？

#### 是否愿意为此组件提交PR？
码农，暂无能力

**Comment by jiaming743** [comment]
[Charts 柱状图实例](http://charts.jiaminghi.com/example/bar.html)这里的柱状图不能满足需要吗？

x轴排列的柱形图，是横着显示的那种柱状图吗，我一般直接用charts配成横着的，如果有类似的效果图是否可以提供一下

图表的底层渲染插件[CRender](http://crender.jiaminghi.com)已经写好了hover，click事件，考虑到工作量和性能，所以暂时没有写对应的逻辑，以后应该会添加类似的支持

**Comment by cangyu1993** [comment]
额。。。。。我是从掘金链接进的DataV，可能没看到其他跳转的链接，嗯，看到了x轴排列的柱状图了
