### ISSUE TITLE
IE不兼容啊，而且有些效果火狐也不兼容

### ISSUE THREAD

**Issue by qiuweikangdev** [jiaming743/DataV#4]

**Comment by Xiaoleng123** [comment]
大屏还是推荐使用 chrome 呢，火狐的问题倒是可以描述详细些，以便作者解决

**Comment by qiuweikangdev** [comment]
<dv-border-box-1>dv-border-box-1</dv-border-box-1> 比如这个组件在火狐中，没有发光闪亮的效果

**Comment by Xiaoleng123** [comment]
> dv-border-box-1 比如这个组件在火狐中，没有发光闪亮的效果

这个其实不是 firefox 不兼容，我看了看代码，其中有一些不很规范（以及大意写错）的写法，这些问题 chrome 会做容错处理，但 firefox 似乎较为严格，直接不生效，已提 PR，等待作者升级

**Comment by Xiaoleng123** [comment]
使用过程中有什么问题期待随时提问哦，这样这个库才会变得更强大更好用哟

**Comment by jiaming743** [comment]
@qiuweikangdev `dv-border-box-1`组件的动画失效已经由 @Xiaoleng123 提交的[(#5)](https://github.com/jiaming743/DataV/pull/5)PR修复，并且针对类似的不兼容情况进行了排查，版本已更新至`v 2.3.6`，文档也已同步进行了修复更新。

由于个人时间和精力的限制，平时只针对chrome浏览器进行了测试，基于兼容难度和稳定性的考虑，建议使用chrome浏览器
