### ISSUE TITLE
dv-border-box-1组件样式异常,不能完全充满容器

### ISSUE THREAD

**Issue by COCOZWY** [jiaming743/DataV#6]

**Comment by COCOZWY** [comment]
这是截图.....
![TIM图片20190826163526](https://user-images.githubusercontent.com/27127505/63677430-8a385600-c81f-11e9-8662-bd43c4eb054b.png)

**Comment by jiaming743** [comment]
父级容器是否设置了`text-align: center`？

**Comment by COCOZWY** [comment]
好了,是加上center属性就行,多谢

**Comment by COCOZWY** [comment]
父级容器确实设置了文本居中

**Comment by jiaming743** [comment]
@COCOZWY 已修复，针对该bug已更新版本至 `v 2.3.7`
