### ISSUE TITLE
启动项目后报错

### ISSUE THREAD

**Issue by sanjinhub** [jiaming743/DataV#7]
Syntax Error: Unexpected token (255:35)

  253 |       }
  254 | 
> 255 |       data = data.map((d, i) => ({ ...d, scroll: i }))
      |                                    ^
  256 | 
  257 |       this.rowsData = data
  258 |       this.rows = data

**Comment by jiaming743** [comment]
看数据好像是轮播表组件吧 请把config数据贴出来 我复现看一下 @sanjinhub

**Comment by jiaming743** [comment]
@sanjinhub 如问题依然存在，请重新发起**Bug report**，按提示完善Bug复现步骤和必要信息，以便于快速定位和解决Bug，感谢使用和支持。
