### ISSUE TITLE
关于react版DataV

### ISSUE THREAD

**Issue by grayguest** [jiaming743/DataV#8]
感谢作者的无私奉献，请问作者有打算出React版DataV吗，或者有啥推荐的，第一眼看到感觉好漂亮，我是名后端人员，对前端不太懂，但最近在学习react

**Comment by jiaming743** [comment]
Vue入门的学习成本是低于React的

而且使用Vue构建完可视化页面后可以将打包好的页面迁移至React工程中去使用，组件库中的组件在实际业务中并不常用，而一些可以在实际业务中使用到的依赖插件如：

* [CRrender](http://crender.jiaminghi.com)
* [Charts](http://charts.jiaminghi.com)
* [Transition](http://transition.jiaminghi.com)

都是纯JS类库，可以在任何框架下使用，而且也有很多开源的，更优秀的同类类库，所以React版本的需求不是很大，由于个人精力的限制所以暂时不会有相关的计划，但也不排除以后可能会有。

**Comment by jiaming743** [comment]
如果有个别组件需要在React中使用，可以查看源码进行转换，也可以联系我提供一些支持

**Comment by grayguest** [comment]
哦哦

**Comment by jiaming743** [comment]
@grayguest React版本需求挺多的，现在已在开发中，正在进行相关测试，近期将会发布，敬请期待

**Comment by yizhiyuyou** [comment]
@grayguest  [React 版本](http://datav.react.jiaminghi.com/guide/)现在可以访问。
