### ISSUE TITLE
要如何获取压缩后的版本

### ISSUE THREAD

**Issue by ToMissYou** [jiaming743/DataV#9]
您好，要如何获取压缩后的版本。谢谢

**Comment by jiaming743** [comment]
文档主页上写的压缩体积是我之前使用`npm publish`命令发布组件库时，npm自动将库打包压缩后的体积，而且由于现在发布时携带了开发源码和编译后文件及README文件，体积会比之前大。而且在实际开发中，Vue应该会自动把你导入的组件进行压缩。文档主页的体积数据已过时，很快将会更新。

**Comment by ToMissYou** [comment]
您好，谢谢您的解答。
不过，我的疑惑是：是想单独使用而不通过node。就如同正常引用
例如：<script type="application/javascript" src="xxx.js"></script>
但是目前我尝试了很多方法都没能正常编译出压缩版的文件。

**Comment by jiaming743** [comment]
后续将推出UMD版，便于`script`标签直接引入，敬请期待

**Comment by jiaming743** [comment]
如果尝试自己打包编译，入口文件应设置为`lib/index.js`

**Comment by ToMissYou** [comment]
好的，谢谢。

**Comment by jiaming743** [comment]
@ToMissYou UMD版 直接可以`script`标签引入的 中午会提到库中的`dist`文件夹中

**Comment by jiaming743** [comment]
@ToMissYou UMD版已上传，不过只是简单编译，没有压缩，以后会优化编译过程，减小编译后体积，可以先用用看，在引入`Vue`的`script`后直接引入，就会自动把组件注册为全局组件，尚未仔细测试，如有问题可以及时反馈
